namespace: default

image:
  repository: harbor.marcmarina.com/library/drizzle-playground
  tag: latest
  pullPolicy: Always

container:
  command: "['node', '.']"
  port: 8080

deployment:
  replicaCount: 1

readinessProbe:
  path: /_health

livenessProbe:
  path: /_health

service:
  type: ClusterIP
  port: 80

ingress:
  host: drizzle-playground.marc-lab.dev

env:
- name: DOTENV_PRIVATE_KEY_PRODUCTION
  valueFrom:
    secretKeyRef:
      name: drizzle-playground-dotenvx-keys
      key: DOTENV_PRIVATE_KEY_PRODUCTION
